### ISSUE TITLE
How do I view suggestions for a misspelled word?

### ISSUE THREAD

**Issue by tbazant** [ChrisChinchilla/vale-vscode#43]
When a word is marked as misspelled, there is no action associated with it to display the small yellow bulb and display available suggestion, or am I doing something wrong?

**Comment by ChrisChinchilla** [comment]
@tbazant So… This does work, but requires a few things, as noted in the read me.

You need to have a spelling-based rule in your rule-set and that rule needs to have an `actions` section to allow for quickfix. For example, like this one: https://github.com/ChrisChinchilla/Openly/blob/main/Openly/Spelling.yml

**Comment by tbazant** [comment]
my rule looks followingly
```
extends: spelling
message: "'%s' may be a typo."
level: error
code: false
dicpath: /usr/share/hunspell
append: true
custom: false
action:
  name: suggest
  params:
    - spellings
dictionaries:
  - en_US-suse-doc
 ```
it matched misspelled words fine, but with no suggestions:
![obrazek](https://github.com/ChrisChinchilla/vale-vscode/assets/2240174/d2fbc334-58f0-4744-8655-7361c8d1c449)
