### ISSUE TITLE
Provide multiple quick fix options with substitution rule

### ISSUE THREAD

**Issue by goerks** [ChrisChinchilla/vale-vscode#7]
Given the following rule
```yml
extends: substitution
message: Use '%s' instead of '%s'
level: error
ignorecase: true
action:
  name: replace
swap:
  whatif: what if|options|more
```
When hover over text `whatif`
![image](https://github.com/ChrisChinchilla/vale-vscode/assets/5419951/bcf4dcdf-af3a-406e-b4e3-e96fd543993e)
Then I expect the substitutions are `what if`, `options` and `more` 🆗 
And I expect a list with these quick fixes `what if`, `options` and `more` ⛔ 
![image](https://github.com/ChrisChinchilla/vale-vscode/assets/5419951/173a298b-c033-44cd-b702-acbc9aa68744)

**Current behavior**
- The first substitution string is contained twice

**Expected behavior**

- Three quick fixes are shown in this order
  1. what if
  2. options
  3. more

**Environment**
- Windows 10
- VSCode 1.79.2
- Vale VSCode v0.17.3

**Comment by ChrisChinchilla** [comment]
I have a fix for this in the next release @goerks 

But @jdkato the issue seems to be deeper in the LSP / CLI that LSP uses, it doesn't seem to return any multiple suggestions in the same format as say, `spelling` does. I have more detail if you need it.

**Comment by jdkato** [comment]
Checked the whole chain against Vale `v3.17.1` and the `vale-ls` bundled in vale-vscode `0.34.0`, using the exact rule from the OP:

```yml
extends: substitution
message: Use '%s' instead of '%s'
level: error
ignorecase: true
action:
  name: replace
swap:
  whatif: what if|options|more
```

**1. CLI JSON output**

```json
"Action": { "Name": "replace", "Params": ["what if", "options", "more"] }
```

**2. `vale fix <alert.json>` (what the LSP shells out to)**

```json
{ "suggestions": ["what if", "options", "more"], "error": "" }
```

**3. `textDocument/codeAction` over real LSP stdio**

```
- Replace with 'what if'
- Replace with 'options'
- Replace with 'more'
```

So nothing is dropping or collapsing them — the original report was against `0.17.3`, back when the extension parsed the message string itself.

One thing that *would* look like "no multiple suggestions": `substitution` only carries an action if the rule declares one. Remove `action: {name: replace}` and the alert comes back as:

```json
"Action": { "Name": "", "Params": null }
```

...which yields zero quick fixes, not one. `spelling` behaves differently because `Vale.Spelling` ships with `suggest`/`spellings` baked in, so it always has an action. Most third-party substitution rules (Google, Microsoft) set none.

If that's the shape you're seeing, it's a style-authoring gap rather than an LSP one.
